pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views , comment_view, questionfree_views,base_views_free

app_name = 'pybo' # namespace를 사용하면 다른 앱의 URL 패턴과 이름이 중복되더라도 문제가 발생하지 않는다.

"""
path 함수의 첫 번째 인수 : URL 패턴

path 함수의 두 번째 인수 : URL 패턴에 매핑되는 뷰 함수

path 함수의 세 번째 인수 : URL 패턴의 별칭

URL 패턴이 비어있는 경우에는 웹 사이트의 기본 URL이다.

웹 사이트의 기본 URL은 웹 사이트에 접속했을 때 가장 먼저 보여지는 페이지이다.

웹 사이트의 기본 URL은 index 함수를 호출한다.

index 함수는 질문 목록을 보여주는 기능을 한다.

"""

urlpatterns = [
###############################################################################################################
    # base_views.py
###############################################################################################################

    # 메인 페이지로 이동 (index 함수 호출)


    path('', base_views.index, name='index'),
    path('free/', base_views_free.index_free, name='index_free'),
    # 질문 상세 페이지로 이동 (question_id를 매개변수로 받아 detail 함수 호출)
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('free/<int:question_id>/', base_views_free.detail_free, name='detail_free'),
    
###############################################################################################################
    # question_views.py
###############################################################################################################

    # 질문 생성 페이지로 이동 (question_create 함수 호출)
    path('question/create/', question_views.question_create, name='question_create'),
    
    # 질문 수정 페이지로 이동 (question_id를 매개변수로 받아 question_modify 함수 호출)
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    
    # 질문 삭제 (question_id를 매개변수로 받아 question_delete 함수 호출)
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    
    # 질문 추천 (question_id를 매개변수로 받아 question_vote 함수 호출)
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    
###############################################################################################################

    #questionfree_view.py
    path('question_free/create/', questionfree_views.question_create, name='questionfree_create'),
    path('question_free/modify/<int:question_id>/', questionfree_views.question_modify, name='questionfree_modify'),
    path('question_free/delete/<int:question_id>/', questionfree_views.question_delete, name='questionfree_delete'),
    path('question_free/vote/<int:question_id>/', questionfree_views.question_vote, name='questionfree_vote'),

    ###############################################################################################################
    #answerfree_view.py
    path('answer_free/create/<int:question_id>/', answer_views.answer_create, name='answerfree_create'),
    path('answer_free/modify/<int:answer_id>/', answer_views.answer_modify, name='answerfree_modify'),
    path('answer_free/delete/<int:answer_id>/', answer_views.answer_delete, name='answerfree_delete'),
    path('answer_free/vote/<int:answer_id>/', answer_views.answer_vote, name='answerfree_vote'),

    # answer_views.py
###############################################################################################################

    # 답변 생성 페이지로 이동 (question_id를 매개변수로 받아 answer_create 함수 호출)
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    
    # 답변 수정 페이지로 이동 (answer_id를 매개변수로 받아 answer_modify 함수 호출)
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    
    # 답변 삭제 (answer_id를 매개변수로 받아 answer_delete 함수 호출)
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    
    # 답변 추천 (answer_id를 매개변수로 받아 answer_vote 함수 호출)
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    
###############################################################################################################
    # comment_views.py
###############################################################################################################

    # 질문에 대한 댓글 생성 (question_id를 매개변수로 받아 comment_create_question 함수 호출)
    path('comment/create/question/<int:question_id>/', comment_view.comment_create_question, name='comment_create_question'),
    
    # 질문에 대한 댓글 수정 (comment_id를 매개변수로 받아 comment_modify_question 함수 호출)
    path('comment/modify/question/<int:comment_id>/', comment_view.comment_modify_question, name='comment_modify_question'),
    
    # 질문에 대한 댓글 삭제 (comment_id를 매개변수로 받아 comment_delete_question 함수 호출)
    path('comment/delete/question/<int:comment_id>/', comment_view.comment_delete_question, name='comment_delete_question'),
    
]

###############################################################################################################

pybo/models.py
import os

from django.db import models
from django.contrib.auth.models import User

# ==========================
# Question 모델 (질문 데이터)
# ==========================
class Question(models.Model):
    # 작성자: User 모델과 다대일 관계 (1명의 사용자가 여러 질문을 작성할 수 있음)
    # on_delete=models.CASCADE: User가 삭제되면 관련 질문도 함께 삭제됨
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    
    # 질문 제목: 최대 200자, 반드시 입력해야 함
    subject = models.CharField(max_length=200, blank=False)
    
    # 질문 내용: 빈 값을 허용하지 않음
    content = models.TextField()
    
    # 질문 작성일시
    create_date = models.DateTimeField()
    
    # 질문 수정일시: 질문이 수정되지 않으면 null 값을 허용함
    modify_date = models.DateTimeField(null=True, blank=True)
    
    # 질문 조회수: 기본값은 0
    view_count = models.PositiveIntegerField(default=0)
    
    # 질문을 추천한 사용자들: 여러 사용자가 추천 가능 (ManyToManyField)
    voter = models.ManyToManyField(User, related_name='voter_question')
    
    # 이미지1: 질문에 첨부된 이미지, null과 빈 값을 허용
    image1 = models.ImageField(upload_to='image1/', null=False, blank=False, verbose_name='업로드 이미지1')
    
    # 이미지2: 질문에 첨부된 두 번째 이미지, null과 빈 값을 허용
    image2 = models.ImageField(upload_to='image2/', null=False, blank=False, verbose_name='업로드 이미지2')

    #save 메서드를 사용해서 기존 파일을 삭제하고 새 파일로 교체
    def save(self,*args,**kwargs):
        from .forms import QuestionForm
        if self.pk:
            old_objects= Question.objects.get(pk=self.pk)
            if old_objects.image1 and old_objects.image1 !=self.image1:
                if os.path.isfile(old_objects.image1.path):
                    os.remove(old_objects.image1.path)
            if old_objects.image2 and old_objects.image2 != self.image2:
                if os.path.isfile(old_objects.image2.path):
                    os.remove(old_objects.image2.path)
        #장고의 save 메세지를 호출하여 모델 인스턴스에 저장
        super(Question,self).save(*args,*kwargs)

    # 객체를 문자열로 표현할 때 질문 제목을 반환
    def __str__(self):
        return self.subject


# ==========================
# Answer 모델 (답변 데이터)
# ==========================
class Answer(models.Model):
    # 작성자: User 모델과 다대일 관계
    # on_delete=models.CASCADE: User가 삭제되면 관련 답변도 삭제됨
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    
    # 답변이 달린 질문과 연결: 질문이 삭제되면 답변도 함께 삭제됨
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    # 답변 내용
    content = models.TextField()
    
    # 답변 작성일시
    create_date = models.DateTimeField()
    
    # 답변 수정일시: 답변이 수정되지 않으면 null 값을 허용
    modify_date = models.DateTimeField(null=True, blank=True)
    
    # 답변을 추천한 사용자들: 여러 사용자가 답변을 추천할 수 있음 (ManyToManyField)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    
    # 답변에 첨부된 이미지, 이미지를 비워둘 수 있음
    answer_image = models.ImageField(upload_to='pybo/answer_image', null=True, blank=True, verbose_name='업로드 이미지')

    # 객체를 문자열로 표현할 때 답변이 달린 질문의 제목을 반환
    def __str__(self):
        return self.question.subject


# ==========================
# Comment 모델 (댓글 및 대댓글 데이터)
# ==========================
class Comment(models.Model):
    # 작성자: User 모델과 다대일 관계
    # on_delete=models.CASCADE: User가 삭제되면 관련 댓글도 삭제됨
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # 댓글 내용
    content = models.TextField()
    
    # 댓글 작성일시
    create_date = models.DateTimeField()
    
    # 댓글 수정일시: 수정되지 않으면 null 값을 허용
    modify_date = models.DateTimeField(null=True, blank=True)
    
    # 댓글이 달린 질문과의 관계: 댓글이 질문에 달린 경우, null과 빈 값을 허용
    question = models.ForeignKey(Question, null=True, blank=True, related_name='comments', on_delete=models.CASCADE)
    
    # 댓글이 달린 답변과의 관계: 댓글이 답변에 달린 경우, null과 빈 값을 허용
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)
    
    # 부모 댓글: 대댓글 기능을 위해 부모 댓글을 참조, null과 빈 값을 허용
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)

    # 객체를 문자열로 표현할 때 댓글 내용의 앞 20자를 반환
    def __str__(self):
        return self.content[:20]



#==============================================
# 자유게시판
#
#==============================================

class Question_Free(models.Model):
    # 작성자: User 모델과 다대일 관계 (1명의 사용자가 여러 질문을 작성할 수 있음)
    # on_delete=models.CASCADE: User가 삭제되면 관련 질문도 함께 삭제됨
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question_free')

    subject = models.CharField(max_length=200, blank=False)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)
    voter = models.ManyToManyField(User, related_name='voter_question_free')
    image1 = models.ImageField(upload_to='image_free/', null=False, blank=False, verbose_name='AI 판단 이미지1')


    # 객체를 문자열로 표현할 때 질문 제목을 반환
    def __str__(self):
        return self.subject



# ==========================
class Answer_Free(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer_free')
    question = models.ForeignKey(Question_Free, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer_free')
    answer_image = models.ImageField(upload_to='ai/answer_image_', null=True, blank=True, verbose_name='업로드 이미지')

    def __str__(self):
        return self.question.subject


class Comment_Free(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question_Free, null=True, blank=True, related_name='comments_free', on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer_Free, null=True, blank=True, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies_free', null=True, blank=True)

    # 객체를 문자열로 표현할 때 댓글 내용의 앞 20자를 반환
    def __str__(self):
        return self.content[:20]

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

########################################################################################################
"""
로그아웃 상태에서는 request.user가 AnonymousUser 객체이므로 에러가 발생할 수 있음 

-> 로그인 상태에서만 질문을 등록할 수 있도록 수정
"""
@login_required(login_url='common:login')
def answer_create(request, question_id):
    ''' pybo 답변등록 '''
    #
    question = get_object_or_404(Question, pk=question_id)
    #
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        #
        if form.is_valid():
            answer = form.save(commit=False)  # commit=False는 데이터베이스에 저장하지 않고 모델 객체만 반환
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            # 
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id)) # answer_{}(앵커)로 이동
            #
        #
    else:
        form = AnswerForm()
        #
    #
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)
    #
#

########################################################################################################

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """ pybo 답변 수정 """
    #
    answer = get_object_or_404(Answer, pk=answer_id)
    #
    if request.user != answer.author:
        messages.error(request, 

        '수정권한이 없습니다'

        )
        #
        return redirect('pybo:detail', question_id=answer.question.id)
        #
    #
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        #
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
            #
        #
    #
    else:
        form = AnswerForm(instance=answer)
        #
    #
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)
    #
#

########################################################################################################

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """ pybo 답변 삭제 """
    #
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, 

        '삭제권한이 없습니다'

        )
        #
    #
    else:
        answer.delete()
        #
    #
    return redirect('pybo:detail', question_id=answer.question.id)
    #
#

########################################################################################################

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    """ pybo 답변 추천 """
    #
    answer = get_object_or_404(Answer, pk=answer_id)
    #
    if request.user == answer.author:
        messages.error(request, 
        
        '본인이 작성한 글은 추천할수 없습니다'
        
        )
        #
    #
    else:
        answer.voter.add(request.user)
        #
    #
    return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    #
#

########################################################################################################

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
import logging
logger = logging.getLogger('pybo')

from ..models import Question, Question_Free

def index(request):
    ''' pybo 목록 출력 '''
    logger.info("INFO 레벨로 출력")
    #
    # 입력인자
    # 페이지 번호를 GET 요청에서 받아옵니다. 기본값은 1로 설정되어 있습니다.
    page = request.GET.get('page', '1')  # GET 방식으로 'page' 값을 받아 page 변수에 할당, 값이 없으면 1을 기본값으로 사용
    #
    # 검색어를 GET 요청에서 받아옵니다. 기본값은 빈 문자열입니다.
    kw = request.GET.get('kw', '')  # 검색어
    #
    # 조회
    # Question 모델에서 모든 질문을 가져와 작성일시(create_date) 역순으로 정렬합니다.
    question_list = Question.objects.order_by('-create_date')  # Question 모델 데이터를 시간 역순으로 정렬
    #
    # 검색어(kw)가 존재할 경우, 제목, 내용, 답변 내용, 질문 글쓴이, 답변 글쓴이에서 검색어를 포함하는 데이터를 필터링합니다.
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목에 검색어 포함된 경우 필터링
            Q(content__icontains=kw) |  # 내용에 검색어 포함된 경우 필터링
            Q(answer__content__icontains=kw) |  # 답변 내용에 검색어 포함된 경우 필터링
            Q(author__username__icontains=kw) |  # 질문 글쓴이 이름에 검색어 포함된 경우 필터링
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 이름에 검색어 포함된 경우 필터링
        ).distinct()  # distinct() 메서드를 사용하여 중복된 질문을 제거합니다.
        #
    #
    # 페이징 처리
    # Paginator 클래스를 사용하여 한 페이지에 10개의 질문을 보여줍니다.
    paginator = Paginator(question_list, 8)  # Paginator 객체 생성 (페이지당 10개 항목)
    #
    # page 번호에 해당하는 페이지의 질문들을 가져옵니다.
    page_obj = paginator.get_page(page)  # 현재 페이지에 해당하는 데이터(page_obj)를 가져옴
    #
    # 템플릿에 전달할 context 딕셔너리를 생성합니다.
    # 'Q_list' 키에 page_obj, 'page' 키에 현재 페이지 번호, 'kw' 키에 검색어를 담습니다.


    context = {'QList': page_obj, 'page': page, 'kw': kw}  # 템플릿에 전달할 데이터
    #
    # pybo/question_list.html 템플릿을 렌더링하고 context 데이터를 전달합니다.
    return render(request, 'pybo/question_list.html', context)  # 렌더링하여 사용자에게 응답
    #
#
def detail(request, question_id):
    ''' pybo 내용 출력 '''
    #
    # 주어진 question_id에 해당하는 Question 객체를 가져옵니다.
    # 객체가 없으면 404 오류를 발생시킵니다.
    question = get_object_or_404(Question, pk=question_id)  # pk로 Question 객체를 가져옴, 없으면 404 오류 발생
    #
    # 템플릿에 전달할 context 딕셔너리를 생성합니다.
    #질문에 있는 댓글을 넘겨줌
    comments = question.comments.filter(parent__isnull=True)
    context = {'question': question, 'comments': comments}  # 템플릿에 전달할 데이터


    return render(request, 'pybo/question_detail.html', context)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
{% comment %} 답변 수정 {% endcomment %}
<div class="container my-3" style="margin-left: 220px">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">
                답변내용
            </label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">
            저장하기
        </button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}

{% block content %}
<div class="container my-3" style="margin-left: 220px">

    {% comment %} 알림 메시지 표시 {% endcomment %}
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
                <strong>{{ message.tags }}</strong>
                <ul><li>{{ message.message }}</li></ul>
            {% endfor %}
        </div>
    {% endif %}

    {% comment %} 질문 제목 {% endcomment %}
    <h2 class="border-bottom py-2">
        {{ question.subject }}
    </h2>

    <div class="card-body">
        {% comment %} 질문 내용 {% endcomment %}
        <div class="card-text">
            {{ question.content|mark }}
        </div>

        {% comment %} 질문 수정 날짜 및 작성자 정보 {% endcomment %}
        <div class="d-flex justify-content-end">
            {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
            {% endif %}
            <div class="badge bg-light text-dark p-2 text-start">
                <div class="mb-2">{{ question.author.username }}</div>
                <div>{{ question.create_date }}</div>
            </div>
        </div>

        {% comment %} 업로드된 이미지 표시 (이미지1) {% endcomment %}
        {% if question.image1 %}
            <div>
                <h5>업로드된 이미지1:</h5>
                <img src="{{ question.image1.url }}" alt="Uploaded Image" style="max-width: 300px; height: auto;">
            </div>
        {% endif %}
        {% comment %} 업로드된 이미지 표시 (이미지2) {% endcomment %}
        {% if question.image2 %}
            <div>
                <h5>업로드된 이미지2:</h5>
                <img src="{{ question.image2.url }}" alt="Uploaded Image" style="max-width: 300px; height: auto;">
            </div>
        {% endif %}

        {% comment %} 추천 버튼 및 수정/삭제 버튼 {% endcomment %}
        <div class="my-3">
            <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id %}" class="recommend btn btn-sm btn-outline-secondary">
                추천
                <span class="badge rounded-pill bg-success">{{ question.voter.count }}</span>
            </a>
            
            {% if request.user == question.author %}
                <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">
                    삭제
                </a>
            {% endif %}
        </div>
    </div>

    {% comment %} 댓글 리스트 표시 {% endcomment %}
    <div class="mt-3">
        {% for comment in comments %}
            <div class="comment py-2 text-muted">
                <span style="white-space: pre-line;">{{ comment.content }}</span>
                <span>
                    - {{ comment.author }}, {{ comment.create_date }}
                    {% if comment.modify_date %} (수정: {{ comment.modify_date }}) {% endif %}
                </span>

                {% if request.user == comment.author %}
                    <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>
                    <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
                {% endif %}
                <a href="{% url 'pybo:comment_create_question' question.id %}" class="small">댓글 달기</a>

                <ul>
                    {% for reply in comment.replies.all %}
                        <li>{{ reply.author }}: {{ reply.content }}</li>
                    {% empty %}
                        <li>No replies yet.</li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>

    <div>
        <a href="{% url 'pybo:comment_create_question' question.id %}" class="small"><small>질문 댓글 추가...</small></a>
    </div>

    {% comment %} 답변 수 표시 {% endcomment %}
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>

    {% comment %} 답변 리스트 표시 {% endcomment %}
    {% for answer in question.answer_set.all %}
        <a id="answer_{{ answer.id }}"></a>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text">
                    {{ answer.content|mark }}
                    {% if question.image1 %}
                    <div>
                        <h5>업로드된 이미지1:</h5>
                        <img src="{{ answer.answer_image.url }}" alt="Uploaded Image" style="max-width: 300px; height: auto;">
                    </div>
                {% endif %}
                </div>
                <div class="d-flex justify-content-end">
                    {% if answer.modify_date %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                    {% endif %}
                    <div class="badge bg-light text-dark p-2 text-start">
                        <div class="mb-2">{{ answer.author.username }}</div>
                        <div>{{ answer.create_date }}</div>
                    </div>
                </div>
                <div class="my-3">
                    <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id %}" class="recommend btn btn-sm btn-outline-secondary">
                        추천
                        <span class="badge rounded-pill bg-success">{{ question.voter.count }}</span>
                    </a>
                    {% if request.user == answer.author %}
                        <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}

    {% comment %} 답변 등록 폼 {% endcomment %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10" {% if not user.is_authenticated %}disabled{% endif %}></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    {% comment %} 삭제 버튼 클릭 시 확인 대화상자 {% endcomment %}
    const delete_elements = document.getElementsByClassName("delete");

    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    {% comment %} 추천 버튼 클릭 시 확인 대화상자 {% endcomment %}
    const recommend_elements = document.getElementsByClassName("recommend");

    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 추천하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}