common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common' # namespace를 사용하면 다른 앱의 URL 패턴과 이름이 중복되더라도 문제가 발생하지 않는다.

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'), # 로그인 처리를 위한 URL 패턴
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views , comment_view, questionfree_views,base_views_free

app_name = 'pybo' # namespace를 사용하면 다른 앱의 URL 패턴과 이름이 중복되더라도 문제가 발생하지 않는다.

"""
path 함수의 첫 번째 인수 : URL 패턴

path 함수의 두 번째 인수 : URL 패턴에 매핑되는 뷰 함수

path 함수의 세 번째 인수 : URL 패턴의 별칭

URL 패턴이 비어있는 경우에는 웹 사이트의 기본 URL이다.

웹 사이트의 기본 URL은 웹 사이트에 접속했을 때 가장 먼저 보여지는 페이지이다.

웹 사이트의 기본 URL은 index 함수를 호출한다.

index 함수는 질문 목록을 보여주는 기능을 한다.

"""

urlpatterns = [
###############################################################################################################
    # base_views.py
###############################################################################################################

    # 메인 페이지로 이동 (index 함수 호출)


    path('', base_views.index, name='index'),
    path('free/', base_views_free.index_free, name='index_free'),
    # 질문 상세 페이지로 이동 (question_id를 매개변수로 받아 detail 함수 호출)
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('free/<int:question_id>/', base_views_free.detail_free, name='detail_free'),
    
###############################################################################################################
    # question_views.py
###############################################################################################################

    # 질문 생성 페이지로 이동 (question_create 함수 호출)
    path('question/create/', question_views.question_create, name='question_create'),
    
    # 질문 수정 페이지로 이동 (question_id를 매개변수로 받아 question_modify 함수 호출)
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    
    # 질문 삭제 (question_id를 매개변수로 받아 question_delete 함수 호출)
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    
    # 질문 추천 (question_id를 매개변수로 받아 question_vote 함수 호출)
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    
###############################################################################################################

    #questionfree_view.py
    path('question_free/create/', questionfree_views.question_create, name='questionfree_create'),
    path('question_free/modify/<int:question_id>/', questionfree_views.question_modify, name='questionfree_modify'),
    path('question_free/delete/<int:question_id>/', questionfree_views.question_delete, name='questionfree_delete'),
    path('question_free/vote/<int:question_id>/', questionfree_views.question_vote, name='questionfree_vote'),

    ###############################################################################################################
    #answerfree_view.py
    path('answer_free/create/<int:question_id>/', answer_views.answer_create, name='answerfree_create'),
    path('answer_free/modify/<int:answer_id>/', answer_views.answer_modify, name='answerfree_modify'),
    path('answer_free/delete/<int:answer_id>/', answer_views.answer_delete, name='answerfree_delete'),
    path('answer_free/vote/<int:answer_id>/', answer_views.answer_vote, name='answerfree_vote'),

    # answer_views.py
###############################################################################################################

    # 답변 생성 페이지로 이동 (question_id를 매개변수로 받아 answer_create 함수 호출)
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    
    # 답변 수정 페이지로 이동 (answer_id를 매개변수로 받아 answer_modify 함수 호출)
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    
    # 답변 삭제 (answer_id를 매개변수로 받아 answer_delete 함수 호출)
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    
    # 답변 추천 (answer_id를 매개변수로 받아 answer_vote 함수 호출)
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    
###############################################################################################################
    # comment_views.py
###############################################################################################################

    # 질문에 대한 댓글 생성 (question_id를 매개변수로 받아 comment_create_question 함수 호출)
    path('comment/create/question/<int:question_id>/', comment_view.comment_create_question, name='comment_create_question'),
    
    # 질문에 대한 댓글 수정 (comment_id를 매개변수로 받아 comment_modify_question 함수 호출)
    path('comment/modify/question/<int:comment_id>/', comment_view.comment_modify_question, name='comment_modify_question'),
    
    # 질문에 대한 댓글 삭제 (comment_id를 매개변수로 받아 comment_delete_question 함수 호출)
    path('comment/delete/question/<int:comment_id>/', comment_view.comment_delete_question, name='comment_delete_question'),
    
]

###############################################################################################################

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
import logging
logger = logging.getLogger('pybo')

from ..models import Question, Question_Free

def index(request):
    ''' pybo 목록 출력 '''
    logger.info("INFO 레벨로 출력")
    #
    # 입력인자
    # 페이지 번호를 GET 요청에서 받아옵니다. 기본값은 1로 설정되어 있습니다.
    page = request.GET.get('page', '1')  # GET 방식으로 'page' 값을 받아 page 변수에 할당, 값이 없으면 1을 기본값으로 사용
    #
    # 검색어를 GET 요청에서 받아옵니다. 기본값은 빈 문자열입니다.
    kw = request.GET.get('kw', '')  # 검색어
    #
    # 조회
    # Question 모델에서 모든 질문을 가져와 작성일시(create_date) 역순으로 정렬합니다.
    question_list = Question.objects.order_by('-create_date')  # Question 모델 데이터를 시간 역순으로 정렬
    #
    # 검색어(kw)가 존재할 경우, 제목, 내용, 답변 내용, 질문 글쓴이, 답변 글쓴이에서 검색어를 포함하는 데이터를 필터링합니다.
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목에 검색어 포함된 경우 필터링
            Q(content__icontains=kw) |  # 내용에 검색어 포함된 경우 필터링
            Q(answer__content__icontains=kw) |  # 답변 내용에 검색어 포함된 경우 필터링
            Q(author__username__icontains=kw) |  # 질문 글쓴이 이름에 검색어 포함된 경우 필터링
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 이름에 검색어 포함된 경우 필터링
        ).distinct()  # distinct() 메서드를 사용하여 중복된 질문을 제거합니다.
        #
    #
    # 페이징 처리
    # Paginator 클래스를 사용하여 한 페이지에 10개의 질문을 보여줍니다.
    paginator = Paginator(question_list, 8)  # Paginator 객체 생성 (페이지당 10개 항목)
    #
    # page 번호에 해당하는 페이지의 질문들을 가져옵니다.
    page_obj = paginator.get_page(page)  # 현재 페이지에 해당하는 데이터(page_obj)를 가져옴
    #
    # 템플릿에 전달할 context 딕셔너리를 생성합니다.
    # 'Q_list' 키에 page_obj, 'page' 키에 현재 페이지 번호, 'kw' 키에 검색어를 담습니다.


    context = {'QList': page_obj, 'page': page, 'kw': kw}  # 템플릿에 전달할 데이터
    #
    # pybo/question_list.html 템플릿을 렌더링하고 context 데이터를 전달합니다.
    return render(request, 'pybo/question_list.html', context)  # 렌더링하여 사용자에게 응답
    #
#
def detail(request, question_id):
    ''' pybo 내용 출력 '''
    #
    # 주어진 question_id에 해당하는 Question 객체를 가져옵니다.
    # 객체가 없으면 404 오류를 발생시킵니다.
    question = get_object_or_404(Question, pk=question_id)  # pk로 Question 객체를 가져옴, 없으면 404 오류 발생
    #
    # 템플릿에 전달할 context 딕셔너리를 생성합니다.
    #질문에 있는 댓글을 넘겨줌
    comments = question.comments.filter(parent__isnull=True)
    context = {'question': question, 'comments': comments}  # 템플릿에 전달할 데이터


    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<title>파이보</title>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% comment %} Bootstrap CSS {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    {% comment %} pybo CSS {% endcomment %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>

    <style>
        .reply-form{
            display: none;
            margin-top : 10px;
        }
        .image-preview {
            max-width : 300px;
            margin-top : 10px;
        }


        .custom-header {
            background-color: #5E5E5E; /* 원하는 색상 */
            color: #FFFFFF; /* 텍스트 색상 */
        }

    </style>
</head>
<body>
    {% include 'navbar.html' %}
    {% comment %} 기본 템플릿 안에 삽입될 내용 Start {% endcomment %}
    {% block content %} 
    {% endblock %}

    {% comment %} 기본 템플릿 안에 삽입될 내용 End {% endcomment %}

    {% comment %} jQuery JS {% endcomment %}
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% comment %} 자바스크립트 Start {% endcomment %}
    {% block script %}
    {% endblock %}
    {% comment %} 자바스크립트 End {% endcomment %}
</body>
</html>

templates/form_errors.html
{% comment %} 필드 오류와 넌필드 오류를 출력한다. {% endcomment %}
{% if form.errors %}
    <div class="alert alert-danger">
        {% for field in form %}
        {% comment %} 필드 오류 {% endcomment %}
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        {% comment %} 넌필드 오류 {% endcomment %}
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/navbar.html
{% comment %} 네비게이션 바 Start {% endcomment %}
<style>
.custom-bg {
    background-color: #FFFFFF; /* 원하는 색상 코드 */
}
.left-navbar{
    position: absolute;
    left: 0;

}

.sidebar {
            height: 100vh; /* 전체 화면 높이 */
            position: fixed; /* 고정된 위치 */
            left: 0; /* 왼쪽에 위치 */
            top: 0; /* 상단에 위치 */
            width: 200px; /* 너비 */
            background-color: #4A90E2; /* 배경색 */
            z-index: 1000;


.navbar-nav {
    display: flex; /* Flexbox 사용 */
    flex-direction: column; /* 세로로 나열 */
    list-style-type: none; /* 기본 리스트 스타일 제거 */
    padding: 0; /* 기본 패딩 제거 */
}

.nav-item {
    margin: 10px 0; /* 각 메뉴 항목 간의 간격 */
}

.nav-link {
    white-space:nowrap;
    text-align: center;

}

.nav-link img {
    margin-right: 8px; /* 아이콘과 텍스트 간의 간격 */
}
</style>

<div class="sidebar">
<nav class="navbar navbar-expand-lg navbar-muted custom-bg border-bottom justify-content-start ">

<!--    <div class="collapse navbar-collapse " id="navbarNav">-->
        <ul class="navbar-nav mx-auto">

              <li class="nav-item">
                    <a class="navbar-brand" href="{% url 'pybo:index' %}">MAIN</a>
                    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </li>

             <li class="nav-item">
                    <a class="nav-link  text-dark" href="{% url 'pybo:index' %}">
                        {% load static %}
                        <img src="{% static 'images/question.png' %}" style="width: 30px; height: 30px;">
                        질문 게시판
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'pybo:index_free' %}">
                        {% load static %}
                        <img src="{% static 'images/free_talking.png' %}" style="width: 30px; height: 30px; ">
                        자유 게시판
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link  text-dark" href="{% url 'pybo:index' %}">
                        <img src="{% static 'images/announcement.png' %}" style="width: 30px; height: 30px; ">
                        공지사항</a>
                </li>
            <li class="nav-item">
                 {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                {% endif %}
            </li>
            <li class="nav-item">
                {% comment %} 현제 사용자가 인증된 경우 사용자 이름과 로그아웃 링크를 출력 {% endcomment %}
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
<!--    </div>-->
</nav>
</div>
<!--<nav class="sidebar">-->
<!--        <div class="navbar-brand text-center">브랜드</div>-->
<!--        <ul class="nav flex-column">-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="#">링크1</a>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="#">링크2</a>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="#">링크3</a>-->
<!--            </li>-->
<!--        </ul>-->
<!--</nav>-->

{% comment %} 네비게이션 바 End {% endcomment %}